### ISSUE TITLE
Build Web App Interface 

### ISSUE THREAD

**Issue by chriswebb09** [chriswebb09/DirectReport#7]
**Is your feature request related to a problem? Please describe.**
We need a way to display the collection of reports so that is it easily readable and searchable. 

**Describe the solution you'd like**
Ideally this needs to be lightweight and build in Node or Flask using Vue or React with CSS Framework like Tailwind.

**Describe alternatives you've considered**
Not applicable. 

**Additional context**
The command line basic functionally should be completed first along with storage and retrieval.

**Comment by unkwnownGriot** [comment]
we should built it with flask it'll be easier

**Comment by chriswebb09** [comment]
Yeah, it makes sense to have as much of the logic in Python as possible.
